services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - .env
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
      - /etc/letsencrypt/live/link.radr.in/fullchain.pem:/etc/letsencrypt/live/link.radr.in/fullchain.pem:ro
      - /etc/letsencrypt/live/link.radr.in/privkey.pem:/etc/letsencrypt/live/link.radr.in/privkey.pem:ro 
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network: