services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - nginx_network

  nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./staticfiles:/code/staticfiles
        - ./media:/code/media
      depends_on:
        - web
      networks:
        - nginx_network

networks:
  nginx_network: