# Generated by Django 5.1.5 on 2025-01-31 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_urlshortener_options_urlshortener_click_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshortener',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'URL Shorteners'},
        ),
        migrations.RemoveField(
            model_name='urlshortener',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='urlshortener',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to=settings.AUTH_USER_MODEL),
        ),
    ]
