# Generated by Django 5.1.5 on 2025-01-30 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshortener',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'URL Shorteners'},
        ),
        migrations.AddField(
            model_name='urlshortener',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urlshortener',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='urlshortener',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='shortened_url',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortened_urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='urlshortener',
            unique_together={('actual_url', 'user')},
        ),
    ]
